### ISSUE TITLE
Enhancment Request: worn/inventory

### ISSUE THREAD

**Issue by random1167** [mcmonkey4eva/Sentinel#74]
hello i see you have 
` player:NAME(REGEX), npc:NAME(REGEX), entityname:NAME(REGEX), helditem:MATERIALNAME(REGEX), group:GROUPNAME(EXACT), event:pvp/pvnpc/pve`
what about the items on players like armor/hats ? and inventory items?

**Comment by mcmonkey4eva** [comment]
the idea behind helditem is so you can watch for holding weapons.
What's the benefit of worn items?

**Comment by random1167** [comment]
illegal armor..say someone is running around with some chain armor or has a common/uncommon block as a hat

**Comment by mcmonkey4eva** [comment]
"illegal armor" wot? Illegal hats too? What?!

**Comment by random1167** [comment]
long story short im trying to make some guards for a prison server..

**Comment by mcmonkey4eva** [comment]
You should probably supplement your Sentinel NPCs with a Denizen script then. http://wiki.citizensnpcs.co/Denizen

Something like this:
```yaml
mynpc:
    type: assignment
    debug: false
    actions:
        on assignment:
        - trigger name:proximity state:true radius:10
        on enter proximity:
        - if <player.equipment.contains_text[chain]> {
          - execute as_server "npc sel <npc.id>" silent
          - execute as_server "sentinel addtarget player:<player.name>" silent
          }
```

**Comment by random1167** [comment]
thank you for sending me in the right direction :heart_eyes:  i'll start researching and testing in the morning,
sorry for any troubles my simple mind may have agrovated  :smile: 
:heart:

**Comment by random1167** [comment]
so playing around with denizen and i know my script is far from complete and rable rable rable. 
running /sentiel forgive the npc still keeps attacking the person who upset the npc LOL

```
NPC:
    type: assignment
    debug: false
    actions:
        on assignment:
        - chat "Duty calls"
        - trigger name:proximity state:true radius:15
        on enter proximity:
        - if <player.inventory.contains[302|303|304|305|357|442|81|373|289|338|46|407|261|385|259|353]> {
          - execute as_server "npc sel <npc.id>" silent
          - execute as_server "sentinel addtarget player:<player.name>" silent
          }
        - trigger name:click state:true
        on click:
        - chat "<red>Get back in line inmate"
```
by the way thank you again for recommending denizen, once i get this down it should be pretty fun

**Comment by mcmonkey4eva** [comment]
Try this:
```yaml
NPC:
    type: assignment
    debug: false
    actions:
        on assignment:
        - chat "Duty calls"
        - trigger name:proximity state:true radius:15
        - trigger name:click state:true
        on enter proximity:
        - if <player.inventory.contains[302|303|304|305|357|442|81|373|289|338|46|407|261|385|259|353]> {
          - execute as_server "npc sel <npc.id>" silent
          - execute as_server "sentinel addtarget player:<player.name>" silent
          }
          else {
          - execute as_server "npc sel <npc.id>" silent
          - execute as_server "sentinel removetarget player:<player.name>" silent
          }
        on click:
        - chat "<red>Get back in line inmate"
```
In particular, the else block.
Optionally throw in a `sentinel forgive` inside the else block as well to make sure all combat ceases.
If you want them to be able to stop the *moment* the player gives up their illegal items,
change `on enter proximity:` to `on move proximity:`
